### ISSUE TITLE
Console error keeps going.

### ISSUE THREAD

**Issue by Sikatsu** [sekwah41/Advanced-Portals#21]
Caused by: java.lang.NullPointerException
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66-internal]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66-internal]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]
org.bukkit.event.EventException
[17:33:34] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to AdvancedPortals v0.0.9

**Comment by Sikatsu** [comment]
I did send you a PM on bukkit. Hope you are able to respond.

**Comment by sekwah41** [comment]
Which build of bukkit are you using? I haven't got round to testing any new ones but someone else was having trouble and they sent me their build so I will test with it once I have my coursework finished.

**Comment by Sikatsu** [comment]
After i compiled the plugin myself using your github, this error is not there anymore. But i'm using Spigot 1.8.8.

**Comment by sekwah41** [comment]
Could be an error from the java verison im using is compiling different or something I am doing. I will try to figure out what is wrong.

**Comment by Sikatsu** [comment]
That might be possible. I didn't check if there were any console errors with your build from the PM, but if i notice errors tomorrow i'll let you know about this. If not, this might is already fixed. I'll get back to this :)

**Comment by Sikatsu** [comment]
I was mistaken. The errors still seems to be here. After a reload or restart it won't show up but as soon as someone will use a portal it keeps spamming my console with this message.

	... 17 more
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
	at sun.reflect.GeneratedMethodAccessor746.invoke(Unknown Source) ~[?:?]
	at com.sekwah.advancedportals.Listeners.onItemInteract(Listeners.java:297) ~[?:?]
Caused by: java.lang.NullPointerException
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66-internal]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66-internal]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]
org.bukkit.event.EventException
[10:58:44] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to AdvancedPortals v0.0.10
[10:58:39] [Server thread/INFO]: RedeemName_[/195.35.244.18:50601] logged in with entity id 765467 at ([world]-5342.379589844413, 75.0, -3772.3031534509378)
[10:58:39] [User Authenticator #26/INFO]: UUID of player RedeemName_ is b607ccdb-0ee2-4025-b0c8-f9efb9c8bd6a
[10:58:36] [Server thread/INFO]: com.mojang.authlib.GameProfile@6fe60041[id=,name=MCI,properties={},legacy=false] (/198.27.83.157:35951) lost connection: Disconnected
	... 17 more
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
	at sun.reflect.GeneratedMethodAccessor746.invoke(Unknown Source) ~[?:?]
	at com.sekwah.advancedportals.Listeners.onItemInteract(Listeners.java:297) ~[?:?]
Caused by: java.lang.NullPointerException
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66-internal]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66-internal]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]
org.bukkit.event.EventException
[10:58:34] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to AdvancedPortals v0.0.10

**Comment by sekwah41** [comment]
Ill take a look and try to figure out what is causing the null pointers, if i cant I will just add some code to catch the null pointers there as there shouldn't be any problems at least in past bukkit versions.

**Comment by Sikatsu** [comment]
Yeah, the plugin is working fine without any issues, really have no idea why it's throwing this error. I don't really have the knowledge for it either, anyways if you fixed it would you mind sharing the build? :)

**Comment by sekwah41** [comment]
Sure, it annoys me when stuff like this happens because parts of the code should stop the additional parts from running like checking when things are null but because of changes to the versions of bukkit and spigot, sometimes the data can be changed so I have to rewrite code to take that into comparison :P 

This is a small error which should be easily fixed but it has caused errors in the past which make it unusable xD

**Comment by Sikatsu** [comment]
I see! I try to understand most of what you say, but my knowledge about it isn't that high about coding, yet. ^^

All i know is that the plugin is working without issues on Spigot 1.8.8 but still giving this error continuesly which makes this bug a important one to fix. Also it might be worth it to place your plugin on the spigot website, way, way better then Bukkit. :)

Thanks!

**Comment by Sikatsu** [comment]
I'm unable to normally read my latest log because this plugin is like non stop shooting out as much errors as possible within seconds. Is there any way to stop this? It's reallt really irritating o.o

**Comment by sekwah41** [comment]
Sadly atm I am unable to replicate these errors even with newer versions. I will try adding some more null statements to try and catch this error and if that doesn't work I will just surround the whole thing with a try statement(which honsetly isnt ideal in case other more fatal errors occour)

**Comment by Sikatsu** [comment]
I hope you are able to fix it soon tho, plugin is workint fine but shooting
so much messages within seconds.. :/

Op di 8 dec. 2015 15:24 schreef sekwah41 <notifications@github.com>:

**Comment by sekwah41** [comment]
Try it again now, I have added 1 new null checker which I think may be causing the problem.

**Comment by sekwah41** [comment]
Try it again now, I have added 1 new null checker which I think may be causing the problem.
http://puu.sh/lOZSI/e067f6b9d7.jar

**Comment by Sikatsu** [comment]
This version is supposed to remove that error? I will try it when i'm home. :)

**Comment by Sikatsu** [comment]
So far it seems not to be giving the error message anymore and everything is still working. Let's hope it will stay this way, otherwise i'll report it again here. :)

**Comment by sekwah41** [comment]
It was what i thought the error may be then :)
