### ISSUE TITLE
1.16.2 - 1.16.4 - not working. (cant see comands)

### ISSUE THREAD

**Issue by DragonRomeo** [sekwah41/Advanced-Portals#227]
On 1.16.2, 16,3, 16,4 - dont work. 
When i use comands i have 1 erorr on all 1.16 versions and i dont see comands in chat and in server's console.
I trying all version this plugin on 1.16+ on 1.16.2 and last version on 1.16.4 (clear server)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
"[14:12:03] [Server thread/ERROR]: Error occurred while enabling AdvancedPortals v0.5.10 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at com.sekwah.advancedportals.bukkit.AdvancedPortalsPlugin.registerCommands(AdvancedPortalsPlugin.java:91) ~[?:?]
	at com.sekwah.advancedportals.bukkit.AdvancedPortalsPlugin.onEnable(AdvancedPortalsPlugin.java:68) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:480) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:426) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:205) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:786) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:155) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	... 12 more"
-----------------------------------------------------------------
Full LOG with only 1 plugin.
-----------------------------------
[14:11:47] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:11:48] [main/INFO]: Reloading ResourceManager: Default, bukkit
[14:11:48] [Worker-Main-12/INFO]: Loaded 7 recipes
[14:11:50] [Server thread/INFO]: Starting minecraft server version 1.16.4
[14:11:50] [Server thread/INFO]: Loading properties
[14:11:50] [Server thread/INFO]: Default game type: SURVIVAL
[14:11:50] [Server thread/INFO]: Generating keypair
[14:11:50] [Server thread/INFO]: Starting Minecraft server on *:25565
[14:11:50] [Server thread/INFO]: Using default channel type
[14:11:51] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-3eb7236 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[14:11:52] [Server thread/INFO]: [AdvancedPortals] Loading AdvancedPortals v0.5.10
[14:11:52] [Server thread/INFO]: Preparing level "world"
[14:11:52] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:11:53] [Server thread/INFO]: Preparing spawn area: 0%
[14:11:53] [Server thread/INFO]: Preparing spawn area: 0%
[14:11:53] [Server thread/INFO]: Preparing spawn area: 0%
[14:11:56] [Worker-Main-9/INFO]: Preparing spawn area: 83%
[14:11:56] [Worker-Main-14/INFO]: Preparing spawn area: 83%
[14:11:56] [Worker-Main-14/INFO]: Preparing spawn area: 83%
[14:11:56] [Worker-Main-14/INFO]: Preparing spawn area: 83%
[14:11:56] [Worker-Main-14/INFO]: Preparing spawn area: 83%
[14:11:56] [Worker-Main-14/INFO]: Preparing spawn area: 83%
[14:11:57] [Worker-Main-15/INFO]: Preparing spawn area: 83%
[14:11:57] [Worker-Main-11/INFO]: Preparing spawn area: 83%
[14:11:58] [Worker-Main-15/INFO]: Preparing spawn area: 83%
[14:11:58] [Worker-Main-9/INFO]: Preparing spawn area: 83%
[14:11:59] [Worker-Main-14/INFO]: Preparing spawn area: 87%
[14:11:59] [Worker-Main-10/INFO]: Preparing spawn area: 95%
[14:12:00] [Server thread/INFO]: Time elapsed: 7334 ms
[14:12:00] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[14:12:00] [Server thread/INFO]: Preparing spawn area: 0%
[14:12:00] [Server thread/INFO]: Preparing spawn area: 0%
[14:12:01] [Worker-Main-10/INFO]: Preparing spawn area: 83%
[14:12:01] [Worker-Main-10/INFO]: Preparing spawn area: 83%
[14:12:02] [Worker-Main-14/INFO]: Preparing spawn area: 83%
[14:12:02] [Worker-Main-13/INFO]: Preparing spawn area: 87%
[14:12:03] [Worker-Main-14/INFO]: Preparing spawn area: 96%
[14:12:03] [Server thread/INFO]: Time elapsed: 3152 ms
[14:12:03] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[14:12:03] [Server thread/INFO]: Preparing spawn area: 0%
[14:12:03] [Server thread/INFO]: Time elapsed: 464 ms
[14:12:03] [Server thread/INFO]: [AdvancedPortals] Enabling AdvancedPortals v0.5.10
[14:12:03] [Server thread/INFO]: [AdvancedPortals] BLOCK_PORTAL_TRAVEL found
[14:12:03] [Server thread/ERROR]: Error occurred while enabling AdvancedPortals v0.5.10 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at com.sekwah.advancedportals.bukkit.AdvancedPortalsPlugin.registerCommands(AdvancedPortalsPlugin.java:91) ~[?:?]
	at com.sekwah.advancedportals.bukkit.AdvancedPortalsPlugin.onEnable(AdvancedPortalsPlugin.java:68) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:480) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:426) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:205) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:786) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:155) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[craftbukkit.jar:git-Bukkit-3eb7236]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	... 12 more
[14:12:03] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:12:03] [Server thread/INFO]: Done (11.269s)! For help, type "help"

**Comment by sekwah41** [comment]
You need to be using SPIGOT not BUKKIT (no one uses bukkit alone anymore... the jar is only generated as part of the build tool process...)

**Comment by DragonRomeo** [comment]
> You need to be using SPIGOT not BUKKIT (no one uses bukkit alone anymore... the jar is only generated as part of the build tool process...)

Oh god. Thank you.

**Comment by sekwah41** [comment]
No problem :D
