### ISSUE TITLE
1.17 support already ?

### ISSUE THREAD

**Issue by comonier** [sekwah41/Advanced-Portals#259]
[14:38:12] [Server thread/ERROR]: Error occurred while enabling AdvancedPortals v0.6.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.configuration.file.YamlConfiguration org.bukkit.Server$Spigot.getPaperConfig()'
	at com.sekwah.advancedportals.bukkit.AdvancedPortalsPlugin.checkIfBungee(AdvancedPortalsPlugin.java:147) ~[?:?]
	at com.sekwah.advancedportals.bukkit.AdvancedPortalsPlugin.setupBungee(AdvancedPortalsPlugin.java:105) ~[?:?]
	at com.sekwah.advancedportals.bukkit.AdvancedPortalsPlugin.onEnable(AdvancedPortalsPlugin.java:70) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3145-Spigot-9472b09-f992ce6]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by sekwah41** [comment]
Are you using paper or normal spigot?

**Comment by LaurenceBarnes** [comment]
Paper is not updated to 1.17 yet

**Comment by sekwah41** [comment]
Hm then if this is spigot then this must be running the paper code by mistake. Ill check it out.

**Comment by comonier** [comment]
> Are you using paper or normal spigot?

[13:20:35] [Server thread/INFO]: This server is running CraftBukkit version 3145-Spigot-9472b09-f992ce6 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
[13:20:35] [Server thread/INFO]: You are running the latest version

**Comment by comonier** [comment]
the plugin is working Everhing is working normal! I just have that console issue when server starts only.

**Comment by sekwah41** [comment]
Ah yea that's just an error thrown in case. I should probably change the message :)

Also make sure you are running the Spigot jar not the CraftBukkit jar. CraftBukkit can cause errors though it sounds like you are on the right one.

**Comment by comonier** [comment]
> Ah yea that's just an error thrown in case. I should probably change the message :)
> 
> Also make sure you are running the Spigot jar not the CraftBukkit jar. CraftBukkit can cause errors though it sounds like you are on the right one.

i am using spigot compiled from buildtools not craftbukkit but that have it on name, but is spigot.

**Comment by comonier** [comment]
The plugin is workinf 100% fine, no erros on server . 

Just that log on startup when it is booting

**Comment by sekwah41** [comment]
Will be published with next pr. Just had a bug with new build pipeline designed to make all this easier :3
