### ISSUE TITLE
Crashes on 1.9.4 works fine on 1.9.2

### ISSUE THREAD

**Issue by glob03** [sekwah41/Advanced-Portals#33]
[12:10:45] [Server thread/INFO]: This version of craftbukkit is not yet supported, please notify the author and give version v:v1_9_R2
[12:10:45] [Server thread/INFO]: [0;31;1mAdvanced portals are being disabled![m
[12:10:45] [Server thread/INFO]: [AdvancedPortals] Sounds found
[12:10:45] [Server thread/ERROR]: Error occurred while enabling AdvancedPortals v0.0.18 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register com.sekwah.advancedportals.listeners.Listeners@1d7e9364 while not enabled
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:524) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at com.sekwah.advancedportals.listeners.Listeners.<init>(Listeners.java:58) ~[?:?]
	at com.sekwah.advancedportals.AdvancedPortalsPlugin.onEnable(AdvancedPortalsPlugin.java:96) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]

**Comment by sekwah41** [comment]
I will have to check it out, It has also been reported by other users. I am not sure why it is crashing as the plugin should be enabled and it works in past versions. I can only assume it is a bug on bukkits side as of now.

I will post more details when I get the time to look.

**Comment by sekwah41** [comment]
Actually your crash log has more info than the last ones I have recieved. I need to stop this part of the plugin activating to make the problem more obvious.

**Comment by sekwah41** [comment]
Actually your crash log has more info than the last ones I have recieved. I need to stop this part of the plugin activating to make the problem more obvious. I will add the version to the nms when possible.

**Comment by sekwah41** [comment]
I have added support for 1.9.4. I will compile it tonight when I get home so I can make it work with Java 7. If you have java 8 then this should work http://puu.sh/oNSqF/8a51ee28ad.jar.

**Comment by glob03** [comment]
Hi, looks like a bit of an minor oversight? I'm off to bed shortly
but I should be around for another 30 mins or so.

[21:10:05] [Server thread/ERROR]: Could not load 
'plugins/AdvancedPortals.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at 
org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) 
~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at 
org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) 
[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at 
org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:296) 
[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at 
net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:200) 
[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at 
net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) 
[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.io.FileNotFoundException: Jar does not contain 
plugin.yml
	... 6 more


On 11-05-2016 20:46, sekwah41 wrote:
> I have added support for 1.9.4. I will compile it tonight when I get
> home so I can make it work with Java 7. If you have java 8 then this
> should work http://puu.sh/oNSqF/8a51ee28ad.jar [1].
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [2]
>
> 	*
>
> Links:
> ------
> [1] http://puu.sh/oNSqF/8a51ee28ad.jar
> [2]
> 
> https://github.com/sekwah41/Advanced-Portals/issues/33#issuecomment-218424701

  Regards
  Greg
-- 
  -[ Registered Linux User #159346 ]-
  http://baratel.com.au/


This Email may contain privileged information and
remains the property of the author. You may not
reveal the contents to anyone without the authors
express authority

Operating System Popularity
https://en.wikipedia.org/wiki/Usage_share_of_operating_systems

Open Source
https://en.wikipedia.org/wiki/Open-source_software
http://www.gnu.org/philosophy/free-software-for-freedom.en.html

**Comment by sekwah41** [comment]
Sorry im on my laptop i must have forgot to fix the plugin.yml

**Comment by sekwah41** [comment]
I will fix the plugin details file later. Sorry about the trouble.

**Comment by sekwah41** [comment]
I uploaded the wrong one. The version I uploaded did not contain the plugin.yml for some reason. Please try this http://puu.sh/oO9LJ/6c5ff89b34.jar it runs at least :)

**Comment by glob03** [comment]
yup, looks like it works fine :) thanks

On 12-05-2016 02:38, sekwah41 wrote:
> I uploaded the wrong one. The version I uploaded did not contain the
> plugin.yml for some reason. Please try this
> http://puu.sh/oO9LJ/6c5ff89b34.jar [1] it runs at least :)
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [2]
>
> 	*
>
> Links:
> ------
> [1] http://puu.sh/oO9LJ/6c5ff89b34.jar
> [2]
> 
> https://github.com/sekwah41/Advanced-Portals/issues/33#issuecomment-218516595

  Regards
  Greg
-- 
  -[ Registered Linux User #159346 ]-
  http://baratel.com.au/


This Email may contain privileged information and
remains the property of the author. You may not
reveal the contents to anyone without the authors
express authority

Operating System Popularity
https://en.wikipedia.org/wiki/Usage_share_of_operating_systems

Open Source
https://en.wikipedia.org/wiki/Open-source_software
http://www.gnu.org/philosophy/free-software-for-freedom.en.html
