### ISSUE TITLE
plugin cannot work on paper 1.19.4

### ISSUE THREAD

**Issue by NetheriteTree** [sekwah41/Advanced-Portals#371]
```bash
[11:33:07 INFO]: [AdvancedPortals] Enabling AdvancedPortals v0.0.41*
[11:33:07 INFO]: [AdvancedPortals] Bukkit version detected v1_19_R3
[11:33:07 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R3.IChatBaseComponent
[11:33:07 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[11:33:07 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[11:33:07 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[11:33:07 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[11:33:07 WARN]:        at java.base/java.lang.Class.forName(Class.java:390)
[11:33:07 WARN]:        at java.base/java.lang.Class.forName(Class.java:381)
[11:33:07 WARN]:        at Advanced-Portals-0.0.41-snapshot.jar//com.sekwah.advancedportals.compat.CraftBukkit.<init>(CraftBukkit.java:48)
[11:33:07 WARN]:        at Advanced-Portals-0.0.41-snapshot.jar//com.sekwah.advancedportals.AdvancedPortalsPlugin.onEnable(AdvancedPortalsPlugin.java:37)
[11:33:07 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[11:33:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[11:33:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[11:33:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[11:33:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:556)
[11:33:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:467)
[11:33:07 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[11:33:07 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[11:33:07 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[11:33:07 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[11:33:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[11:33:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[11:33:07 WARN]: [AdvancedPortals] Attempting to use backup porekit locations
[11:33:07 WARN]: java.lang.ClassNotFoundException: net.minecraft.util.text.ITextComponent
[11:33:07 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[11:33:07 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[11:33:07 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[11:33:07 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[11:33:07 WARN]:        at java.base/java.lang.Class.forName(Class.java:390)
[11:33:07 WARN]:        at java.base/java.lang.Class.forName(Class.java:381)
[11:33:07 WARN]:        at Advanced-Portals-0.0.41-snapshot.jar//com.sekwah.advancedportals.compat.CraftBukkit.<init>(CraftBukkit.java:87)
[11:33:07 WARN]:        at Advanced-Portals-0.0.41-snapshot.jar//com.sekwah.advancedportals.AdvancedPortalsPlugin.onEnable(AdvancedPortalsPlugin.java:37)
[11:33:07 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[11:33:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[11:33:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[11:33:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[11:33:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:556)
[11:33:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:467)
[11:33:07 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[11:33:07 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[11:33:07 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[11:33:07 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[11:33:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[11:33:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[11:33:07 WARN]: [AdvancedPortals] This version of craftbukkit is not yet supported, please notify sekwah and tell him about this version v:v1_19_R3
[11:33:07 WARN]: [AdvancedPortals] Along with the above stacktrace
[11:33:07 INFO]: Advanced portals are being disabled!
```
paper version: git-Paper-530 (MC: 1.19.4)
plugin version: 0.0.41 (latest)

**Comment by sekwah41** [comment]
Hey, 0.0.41 isn't the latest. That supports 1.7-1.12. You need 0.9.2

**Comment by sekwah41** [comment]
Modrinth seems to have them listed in the wrong order but they do show which mc they support ![image](https://github.com/sekwah41/Advanced-Portals/assets/3209834/1e0f5fd5-82d1-4cab-8547-a6a9199c2017)
