### ISSUE TITLE
Config.yml to config.yaml issue when upgrading

### ISSUE THREAD

**Issue by pschapman** [sekwah41/Advanced-Portals#484]
Upgrading from 1.0.0. to 2.0.x does not transfer settings. I get that not all features survived the upgrade. Change will be easier if equivalencies are recognized and automatically imported. 

Old: `PortalProtectionArea: 1`
New: `portalProtectionRaduis: 5` <-- Note misspelling of radius

Inline documentation is also absent.

**Comment by sekwah41** [comment]
Due to a lot of changes I didn't port the config importing. Though I will add it to the command to pull what it can as we can read the old files.

**Comment by sekwah41** [comment]
<img width="1009" alt="Screenshot 2024-12-15 at 4 25 16 AM" src="https://github.com/user-attachments/assets/d472437c-e7b2-4e9e-a12f-90ac740d24ce" />
this was the original message but i made it auto import so it doesn't show,

**Comment by sekwah41** [comment]
[Advanced-Portals-2.0.3-config-import-81f5df2b.jar.zip](https://github.com/user-attachments/files/18139028/Advanced-Portals-2.0.3-config-import-81f5df2b.jar.zip)
Hey could you give this a go. It will overwrite your config but should import all the supported values

**Comment by pschapman** [comment]
Hi -

Added custom build you provided to my server. AP plugin failed to load with the following message:
```
[03:05:09] [Server thread/INFO]: [AdvancedPortals] Enabling AdvancedPortals v2.0.3-config-import-81f5df2b
[03:05:09] [Server thread/INFO]: [AdvancedPortals] Loading Advanced Portals Core v2.0.3-config-import-81f5df2b for MC: 1.21.4
[03:05:10] [Server thread/INFO]: [AdvancedPortals] Importing old destinations from destinations.yml
[03:05:10] [Server thread/INFO]: [AdvancedPortals] Importing old portals from portals.yml
[03:05:10] [Server thread/ERROR]: Error occurred while enabling AdvancedPortals v2.0.3-config-import-81f5df2b (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.sekwah.advancedportals.core.serializeddata.DataStorage.storeFile(Object, String)" because "this.dataStorage" is null
        at com.sekwah.advancedportals.core.repository.impl.ConfigRepositoryImpl.storeConfig(ConfigRepositoryImpl.java:159) ~[?:?]
        at com.sekwah.advancedportals.core.repository.impl.ConfigRepositoryImpl.importConfig(ConfigRepositoryImpl.java:164) ~[?:?]
        at com.sekwah.advancedportals.spigot.importer.LegacyImporter.importConfig(LegacyImporter.java:184) ~[?:?]
        at com.sekwah.advancedportals.spigot.AdvancedPortalsPlugin.checkAndCreateConfig(AdvancedPortalsPlugin.java:121) ~[?:?]
        at com.sekwah.advancedportals.spigot.AdvancedPortalsPlugin.onEnable(AdvancedPortalsPlugin.java:83) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R3.CraftServer.enablePlugin(CraftServer.java:579) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4402-Spigot-33ece3e-665900b]
        at org.bukkit.craftbukkit.v1_21_R3.CraftServer.enablePlugins(CraftServer.java:493) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4402-Spigot-33ece3e-665900b]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:656) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4402-Spigot-33ece3e-665900b]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4402-Spigot-33ece3e-665900b]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:268) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4402-Spigot-33ece3e-665900b]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1032) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4402-Spigot-33ece3e-665900b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[spigot-1.21.4-R0.1-SNAPSHOT.jar:4402-Spigot-33ece3e-665900b]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

-PSC

**Comment by sekwah41** [comment]
Forgot to close the issue but its fixed now :D
