### ISSUE TITLE
Error, then the plugin was disabled...

### ISSUE THREAD

**Issue by accpclair** [sekwah41/Advanced-Portals#59]
Good evening! I would like to ask for your help in enabling the plugin. It suddenly does not work while I was configuring my server and it displayed that there is an internal error. I rebooted the server, and the plugin doesn't work. Here is the part of the log that displays the error:

   [15:09:51] [Server thread/WARN]: java.lang.IllegalArgumentException: Name cannot be null
   [15:09:51] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
   [15:09:51] [Server thread/WARN]: 	at 
org.bukkit.craftbukkit.v1_11_R1.CraftServer.getWorld(CraftServer.java:977)
   [15:09:51] [Server thread/WARN]: 	at org.bukkit.Bukkit.getWorld(Bukkit.java:510)
   [15:09:51] [Server thread/WARN]: 	at com.sekwah.advancedportals.portals.Portal.loadPortals(Portal.java:97)
[15:09:51] [Server thread/WARN]: 	at com.sekwah.advancedportals.portals.Portal.<init>(Portal.java:40)
[15:09:51] [Server thread/WARN]: 	at com.sekwah.advancedportals.AdvancedPortalsPlugin.onEnable(AdvancedPortalsPlugin.java:45)
[15:09:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[15:09:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329)
[15:09:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[15:09:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:361)
[15:09:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323)
[15:09:51] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:411)
[15:09:51] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:372)
[15:09:51] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:327)
[15:09:51] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:244)
[15:09:51] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521)
[15:09:51] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:09:51] [Server thread/WARN]: [AdvancedPortals] Something went wrong, please notify sekwah and tell him about this version v:v1_11_R1
[15:09:51] [Server thread/WARN]: [AdvancedPortals] Along with the above stacktrace
[15:09:51] [Server thread/INFO]: [0;31;1mAdvanced portals are being disabled![m

Unfortunately, I'm a newbie at this so I hope you can enlighten me about it so I can fix it myself, the next time it happens. Thanks in advance!

**Comment by sekwah41** [comment]
Remove the portal plugin folder. For some reason it is trying to load a portal from a world which isnt loaded. I will add some nullpointers for the next update to stop this crash but for now just get rid of the folder because some portals have invalid data.

**Comment by sekwah41** [comment]
Actually better yet try this, I made a quick test version for you. I haven't properly tested it but if it starts up it should be fine. If it doesn't work ill test it when I can to fix the issue.
[Null portal fix.zip](https://github.com/sekwah41/Advanced-Portals/files/1011360/Null.portal.fix.zip)

**Comment by accpclair** [comment]
Removing the plugin folder seems to fix it. Thanks!

**Comment by sekwah41** [comment]
I have made a working fix now for if this error ever comes up again. The portal will just be ignored all together. That way removing worlds will no longer cause issues.
